services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=67.207.89.85
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=[http://67.207.89.85:5678/](http://67.207.89.85:5678/)
      - GENERIC_TIMEZONE=America/New_York
    volumes:
      - n8n_data:/home/node/.local/share/n8n

volumes:
  n8n_data:
